services:
  tc:
    image: "${DOCKER_IMAGE_TERMINAL:-ethanvdh/docker-tc}"
    container_name: docker-tc
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global
      restart_policy:
        condition: any
    network_mode: host
    pid: host
